import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { RootProvider } from "fumadocs-ui/provider/next";
import { SiteNavbar } from "@/components/nav-implementation";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col w-screen h-screen overflow-hidden flex flex-col">
        <RootProvider
          theme={{
            defaultTheme: "light",
            enableSystem: false,
            forcedTheme: "light",
          }}
        >
          <SiteNavbar />
          <div className="w-full flex-1 overflow-y-scroll">{children}</div>
        </RootProvider>
      </body>
    </html>
  );
}
